"""initial migration

Revision ID: 12887883e2cf
Revises: 
Create Date: 2023-12-10 22:12:57.110003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12887883e2cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enemies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('mp', sa.Integer(), nullable=True),
    sa.Column('atk', sa.Integer(), nullable=True),
    sa.Column('matk', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('pfp', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('coins', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('background', sa.String(), nullable=True),
    sa.Column('rug', sa.String(), nullable=True),
    sa.Column('banner', sa.String(), nullable=True),
    sa.Column('chair', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bases_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('mp', sa.Integer(), nullable=True),
    sa.Column('atk', sa.Integer(), nullable=True),
    sa.Column('matk', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('exp', sa.Integer(), nullable=True),
    sa.Column('job', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_characters_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], name=op.f('fk_friends_friend_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_friends_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('fk_messages_receiver_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('stat', sa.String(), nullable=True),
    sa.Column('boost', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('enemy_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_equipment_character_id_characters')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['friends.id'], name=op.f('fk_friends_association_friend_id_friends')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_friends_association_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('enemy_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_items_character_id_characters')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_messages_association_message_id_messages')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_messages_association_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'message_id')
    )
    op.create_table('drops_association',
    sa.Column('enemy_id', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.Integer(), nullable=True),
    sa.Column('item_1', sa.Integer(), nullable=True),
    sa.Column('item_2', sa.Integer(), nullable=True),
    sa.Column('item_3', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['enemy_id'], ['enemies.id'], name=op.f('fk_drops_association_enemy_id_enemies')),
    sa.ForeignKeyConstraint(['equipment'], ['equipment.id'], name=op.f('fk_drops_association_equipment_equipment')),
    sa.ForeignKeyConstraint(['item_1'], ['items.id'], name=op.f('fk_drops_association_item_1_items')),
    sa.ForeignKeyConstraint(['item_2'], ['items.id'], name=op.f('fk_drops_association_item_2_items')),
    sa.ForeignKeyConstraint(['item_3'], ['items.id'], name=op.f('fk_drops_association_item_3_items'))
    )
    op.create_table('equipment_association',
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_equipment_association_character_id_characters')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_equipment_association_equipment_id_equipment'))
    )
    op.create_table('items_association',
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_items_association_character_id_characters')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_items_association_item_id_items'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_association')
    op.drop_table('equipment_association')
    op.drop_table('drops_association')
    op.drop_table('messages_association')
    op.drop_table('items')
    op.drop_table('friends_association')
    op.drop_table('equipment')
    op.drop_table('messages')
    op.drop_table('friends')
    op.drop_table('characters')
    op.drop_table('bases')
    op.drop_table('users')
    op.drop_table('enemies')
    # ### end Alembic commands ###
