"""changes to enemy table

Revision ID: 15de1ebb8bd3
Revises: da4365f56f7e
Create Date: 2023-12-18 03:30:44.943789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15de1ebb8bd3'
down_revision = 'da4365f56f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drops_association', schema=None) as batch_op:
        batch_op.drop_constraint('fk_drops_association_equipment_id_equipment', type_='foreignkey')
        batch_op.drop_column('equipment_id')

    with op.batch_alter_table('enemies', schema=None) as batch_op:
        batch_op.drop_column('mp')
        batch_op.drop_column('level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enemies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('mp', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('drops_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_drops_association_equipment_id_equipment', 'equipment', ['equipment_id'], ['id'])

    # ### end Alembic commands ###
