"""updated messages & inbox schemas

Revision ID: 2023c881e0ff
Revises: 9368373332ac
Create Date: 2024-02-29 09:03:46.414107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2023c881e0ff'
down_revision = '9368373332ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inbox_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_inboxes_sender_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_inboxes_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_inboxes_inbox_id_users'), 'users', ['inbox_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('sender_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_from', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sent_to', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_messages_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_messages_inbox_id_inboxes', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_messages_sent_from_users'), 'users', ['sent_from'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_messages_sent_to_users'), 'users', ['sent_to'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('inbox_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inbox_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_messages_sent_to_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_messages_sent_from_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_messages_inbox_id_inboxes', 'inboxes', ['inbox_id'], ['id'])
        batch_op.create_foreign_key('fk_messages_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('sent_to')
        batch_op.drop_column('sent_from')

    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_inboxes_inbox_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_inboxes_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_inboxes_sender_id_users', 'users', ['sender_id'], ['id'])
        batch_op.drop_column('inbox_id')

    # ### end Alembic commands ###
