"""to up/down vote comments

Revision ID: 2ce9d93d7bae
Revises: 4528c6924d18
Create Date: 2023-11-16 17:29:04.996513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce9d93d7bae'
down_revision = '4528c6924d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comment_score', sa.Integer(), nullable=True))
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.INTEGER(), nullable=True))
        batch_op.drop_column('comment_score')
        batch_op.drop_column('game_score')

    # ### end Alembic commands ###
