"""removed character.name

Revision ID: 31ffe0dbd8ee
Revises: 12887883e2cf
Create Date: 2023-12-13 06:12:53.856877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ffe0dbd8ee'
down_revision = '12887883e2cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('drops_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_drops_association_item_1_items', type_='foreignkey')
        batch_op.drop_constraint('fk_drops_association_item_2_items', type_='foreignkey')
        batch_op.drop_constraint('fk_drops_association_item_3_items', type_='foreignkey')
        batch_op.drop_constraint('fk_drops_association_equipment_equipment', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_drops_association_equipment_id_equipment'), 'equipment', ['equipment_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_drops_association_item_id_items'), 'items', ['item_id'], ['id'])
        batch_op.drop_column('item_3')
        batch_op.drop_column('equipment')
        batch_op.drop_column('item_1')
        batch_op.drop_column('item_2')

    with op.batch_alter_table('enemies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coins', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enemies', schema=None) as batch_op:
        batch_op.drop_column('coins')

    with op.batch_alter_table('drops_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_2', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('item_1', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('equipment', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('item_3', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_drops_association_item_id_items'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_drops_association_equipment_id_equipment'), type_='foreignkey')
        batch_op.create_foreign_key('fk_drops_association_equipment_equipment', 'equipment', ['equipment'], ['id'])
        batch_op.create_foreign_key('fk_drops_association_item_3_items', 'items', ['item_3'], ['id'])
        batch_op.create_foreign_key('fk_drops_association_item_2_items', 'items', ['item_2'], ['id'])
        batch_op.create_foreign_key('fk_drops_association_item_1_items', 'items', ['item_1'], ['id'])
        batch_op.drop_column('item_id')
        batch_op.drop_column('equipment_id')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
