"""moves table

Revision ID: 44f2d623f521
Revises: 6a5e507d780a
Create Date: 2023-12-23 15:07:27.727055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f2d623f521'
down_revision = '6a5e507d780a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('job', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('accuraccy', sa.Integer(), nullable=True),
    sa.Column('base', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    # ### end Alembic commands ###
