"""forgor to add image column to enemy table

Revision ID: 6a5e507d780a
Revises: 7055792daefe
Create Date: 2023-12-18 03:39:13.348739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5e507d780a'
down_revision = '7055792daefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enemies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enemies', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
