"""changed base model

Revision ID: 70d38dcacb32
Revises: 0a85c2599b8a
Create Date: 2024-01-26 08:37:23.194345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d38dcacb32'
down_revision = '0a85c2599b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wall_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rug_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('furniture_1_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('furniture_2_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('furniture_3_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_bases_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_bases_furniture_1_id_items'), 'items', ['furniture_1_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_bases_furniture_3_id_items'), 'items', ['furniture_3_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_bases_wall_id_items'), 'items', ['wall_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_bases_rug_id_items'), 'items', ['rug_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_bases_furniture_2_id_items'), 'items', ['furniture_2_id'], ['id'])
        batch_op.drop_column('wall')
        batch_op.drop_column('furniture_2')
        batch_op.drop_column('furniture_1')
        batch_op.drop_column('furniture_3')
        batch_op.drop_column('rug')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rug', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('furniture_3', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('furniture_1', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('furniture_2', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('wall', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_bases_furniture_2_id_items'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_bases_rug_id_items'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_bases_wall_id_items'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_bases_furniture_3_id_items'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_bases_furniture_1_id_items'), type_='foreignkey')
        batch_op.create_foreign_key('fk_bases_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('furniture_3_id')
        batch_op.drop_column('furniture_2_id')
        batch_op.drop_column('furniture_1_id')
        batch_op.drop_column('rug_id')
        batch_op.drop_column('wall_id')

    # ### end Alembic commands ###
