"""need max hp/mp columns

Revision ID: a758d61de5ae
Revises: 7c650a90a8be
Create Date: 2024-02-04 03:40:29.996086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a758d61de5ae'
down_revision = '7c650a90a8be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_hp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_mp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('max_mp')
        batch_op.drop_column('max_hp')

    # ### end Alembic commands ###
