"""added row to handle realtime server

Revision ID: aedc1f78da41
Revises: bef06970a71c
Create Date: 2024-03-16 18:02:02.869291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aedc1f78da41'
down_revision = 'bef06970a71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_server', schema=None) as batch_op:
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###
