"""inboxes again

Revision ID: cdcf112c019a
Revises: 2e8f2e534319
Create Date: 2023-12-14 10:02:39.109199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcf112c019a'
down_revision = '2e8f2e534319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_sender_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_messages_receiver_id_users', type_='foreignkey')
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('receiver_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_messages_receiver_id_users', 'users', ['receiver_id'], ['id'])
        batch_op.create_foreign_key('fk_messages_sender_id_users', 'users', ['sender_id'], ['id'])

    # ### end Alembic commands ###
