"""moar item changes

Revision ID: da4365f56f7e
Revises: f79a450fc5d1
Create Date: 2023-12-17 09:24:31.801680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4365f56f7e'
down_revision = 'f79a450fc5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_items_character_id_characters', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_items_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('character_id')

    with op.batch_alter_table('items_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_items_association_character_id_characters', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_items_association_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_items_association_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_items_association_character_id_characters', 'characters', ['character_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_items_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_items_character_id_characters', 'characters', ['character_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
