"""name changed to not be confusing

Revision ID: db310e70f2a2
Revises: 2023c881e0ff
Create Date: 2024-02-29 09:52:33.937872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db310e70f2a2'
down_revision = '2023c881e0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_inboxes_inbox_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_inboxes_owner_id_users'), 'users', ['owner_id'], ['id'])
        batch_op.drop_column('inbox_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inboxes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inbox_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_inboxes_owner_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_inboxes_inbox_id_users', 'users', ['inbox_id'], ['id'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
