"""added row to items table

Revision ID: dd7e6b6bd60a
Revises: afdf1d32f553
Create Date: 2024-01-30 07:45:33.034827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7e6b6bd60a'
down_revision = 'afdf1d32f553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
