"""changed base model

Revision ID: e09cd95123e2
Revises: 6c2bf5c42b40
Create Date: 2024-01-10 18:11:13.643972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09cd95123e2'
down_revision = '6c2bf5c42b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('furniture_1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('furniture_2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('furniture_3', sa.String(), nullable=True))
        batch_op.drop_column('background')
        batch_op.drop_column('chair')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chair', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('background', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('furniture_3')
        batch_op.drop_column('furniture_2')
        batch_op.drop_column('furniture_1')

    # ### end Alembic commands ###
