"""more changes to items

Revision ID: f79a450fc5d1
Revises: ee6a9b3bb524
Create Date: 2023-12-17 07:22:14.245538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79a450fc5d1'
down_revision = 'ee6a9b3bb524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.drop_column('action')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
